/*
 * generated by Xtext 2.11.0
 */
package org.lilychant.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LilyChantGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ScriptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.Script");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTonesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTonesToneParserRuleCall_0_0 = (RuleCall)cTonesAssignment_0.eContents().get(0);
		private final Assignment cChantsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cChantsChantParserRuleCall_1_0 = (RuleCall)cChantsAssignment_1.eContents().get(0);
		
		//Script:
		//	tones+=Tone*
		//	//	ensemble=Ensemble
		//	chants+=Chant*;
		@Override public ParserRule getRule() { return rule; }
		
		//tones+=Tone* //	ensemble=Ensemble
		//chants+=Chant*
		public Group getGroup() { return cGroup; }
		
		//tones+=Tone*
		public Assignment getTonesAssignment_0() { return cTonesAssignment_0; }
		
		//Tone
		public RuleCall getTonesToneParserRuleCall_0_0() { return cTonesToneParserRuleCall_0_0; }
		
		////	ensemble=Ensemble
		//chants+=Chant*
		public Assignment getChantsAssignment_1() { return cChantsAssignment_1; }
		
		//Chant
		public RuleCall getChantsChantParserRuleCall_1_0() { return cChantsChantParserRuleCall_1_0; }
	}
	public class ToneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.Tone");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cToneKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cVoicesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cBEGINTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cVoiceNamesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cVoiceNamesVoiceNameParserRuleCall_5_0 = (RuleCall)cVoiceNamesAssignment_5.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cPhrasesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPhrasesTonePhraseParserRuleCall_7_0 = (RuleCall)cPhrasesAssignment_7.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		
		///*
		// * Tone definitions
		// */ // TODO VOICE NAMES SHOULD BE GLOBAL
		//Tone:
		//	'Tone' name=ID //'key' key=ID
		//	BEGIN
		//	'Voices'
		//	BEGIN
		//	voiceNames+=VoiceName+
		//	END
		//	phrases+=TonePhrase+
		//	END;
		@Override public ParserRule getRule() { return rule; }
		
		//'Tone' name=ID //'key' key=ID
		//BEGIN 'Voices' BEGIN voiceNames+=VoiceName+ END phrases+=TonePhrase+ END
		public Group getGroup() { return cGroup; }
		
		//'Tone'
		public Keyword getToneKeyword_0() { return cToneKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		////'key' key=ID
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_2() { return cBEGINTerminalRuleCall_2; }
		
		//'Voices'
		public Keyword getVoicesKeyword_3() { return cVoicesKeyword_3; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_4() { return cBEGINTerminalRuleCall_4; }
		
		//voiceNames+=VoiceName+
		public Assignment getVoiceNamesAssignment_5() { return cVoiceNamesAssignment_5; }
		
		//VoiceName
		public RuleCall getVoiceNamesVoiceNameParserRuleCall_5_0() { return cVoiceNamesVoiceNameParserRuleCall_5_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_6() { return cENDTerminalRuleCall_6; }
		
		//phrases+=TonePhrase+
		public Assignment getPhrasesAssignment_7() { return cPhrasesAssignment_7; }
		
		//TonePhrase
		public RuleCall getPhrasesTonePhraseParserRuleCall_7_0() { return cPhrasesTonePhraseParserRuleCall_7_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_8() { return cENDTerminalRuleCall_8; }
	}
	public class VoiceNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.VoiceName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//VoiceName:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class TonePhraseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.TonePhrase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPhraseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cVoicesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVoicesVoicePhraseParserRuleCall_3_0 = (RuleCall)cVoicesAssignment_3.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//TonePhrase:
		//	'Phrase' name=ID
		//	BEGIN
		//	voices+=VoicePhrase+
		//	END;
		@Override public ParserRule getRule() { return rule; }
		
		//'Phrase' name=ID BEGIN voices+=VoicePhrase+ END
		public Group getGroup() { return cGroup; }
		
		//'Phrase'
		public Keyword getPhraseKeyword_0() { return cPhraseKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_2() { return cBEGINTerminalRuleCall_2; }
		
		//voices+=VoicePhrase+
		public Assignment getVoicesAssignment_3() { return cVoicesAssignment_3; }
		
		//VoicePhrase
		public RuleCall getVoicesVoicePhraseParserRuleCall_3_0() { return cVoicesVoicePhraseParserRuleCall_3_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_4() { return cENDTerminalRuleCall_4; }
	}
	public class VoicePhraseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.VoicePhrase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVoiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cNameVoiceNameCrossReference_1_0 = (CrossReference)cNameAssignment_1.eContents().get(0);
		private final RuleCall cNameVoiceNameIDTerminalRuleCall_1_0_1 = (RuleCall)cNameVoiceNameCrossReference_1_0.eContents().get(1);
		private final RuleCall cBEGINTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cNotesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNotesNoteParserRuleCall_3_0 = (RuleCall)cNotesAssignment_3.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//VoicePhrase:
		//	'Voice' name=[VoiceName] BEGIN
		//	notes+=Note+
		//	END;
		@Override public ParserRule getRule() { return rule; }
		
		//'Voice' name=[VoiceName] BEGIN notes+=Note+ END
		public Group getGroup() { return cGroup; }
		
		//'Voice'
		public Keyword getVoiceKeyword_0() { return cVoiceKeyword_0; }
		
		//name=[VoiceName]
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//[VoiceName]
		public CrossReference getNameVoiceNameCrossReference_1_0() { return cNameVoiceNameCrossReference_1_0; }
		
		//ID
		public RuleCall getNameVoiceNameIDTerminalRuleCall_1_0_1() { return cNameVoiceNameIDTerminalRuleCall_1_0_1; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_2() { return cBEGINTerminalRuleCall_2; }
		
		//notes+=Note+
		public Assignment getNotesAssignment_3() { return cNotesAssignment_3; }
		
		//Note
		public RuleCall getNotesNoteParserRuleCall_3_0() { return cNotesNoteParserRuleCall_3_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_4() { return cENDTerminalRuleCall_4; }
	}
	public class ChantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.Chant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChantKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cToneKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cToneAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cToneToneCrossReference_3_0 = (CrossReference)cToneAssignment_3.eContents().get(0);
		private final RuleCall cToneToneIDTerminalRuleCall_3_0_1 = (RuleCall)cToneToneCrossReference_3_0.eContents().get(1);
		private final RuleCall cBEGINTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cPhrasesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPhrasesLyricPhraseParserRuleCall_5_0 = (RuleCall)cPhrasesAssignment_5.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		
		/////*
		//// * Ensemble
		//// */
		////
		////Ensemble:
		////	'ensemble' ':'
		////	'top' 'staff' ':' BEGIN voices+=[VoiceName]+ END
		////	'bottom' 'staff' ':' BEGIN voices+=[VoiceName]+ END
		////;
		///*
		// * Chants
		// */ Chant:
		//	'Chant' name=STRING? 'Tone' tone=[Tone] BEGIN
		//	phrases+=LyricPhrase+
		//	END;
		@Override public ParserRule getRule() { return rule; }
		
		//'Chant' name=STRING? 'Tone' tone=[Tone] BEGIN phrases+=LyricPhrase+ END
		public Group getGroup() { return cGroup; }
		
		//'Chant'
		public Keyword getChantKeyword_0() { return cChantKeyword_0; }
		
		//name=STRING?
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'Tone'
		public Keyword getToneKeyword_2() { return cToneKeyword_2; }
		
		//tone=[Tone]
		public Assignment getToneAssignment_3() { return cToneAssignment_3; }
		
		//[Tone]
		public CrossReference getToneToneCrossReference_3_0() { return cToneToneCrossReference_3_0; }
		
		//ID
		public RuleCall getToneToneIDTerminalRuleCall_3_0_1() { return cToneToneIDTerminalRuleCall_3_0_1; }
		
		////'key' key=ID
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_4() { return cBEGINTerminalRuleCall_4; }
		
		//phrases+=LyricPhrase+
		public Assignment getPhrasesAssignment_5() { return cPhrasesAssignment_5; }
		
		//LyricPhrase
		public RuleCall getPhrasesLyricPhraseParserRuleCall_5_0() { return cPhrasesLyricPhraseParserRuleCall_5_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_6() { return cENDTerminalRuleCall_6; }
	}
	public class LyricPhraseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.LyricPhrase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cExplicitPhraseAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final CrossReference cExplicitPhraseTonePhraseCrossReference_0_1_0 = (CrossReference)cExplicitPhraseAssignment_0_1.eContents().get(0);
		private final RuleCall cExplicitPhraseTonePhraseIDTerminalRuleCall_0_1_0_1 = (RuleCall)cExplicitPhraseTonePhraseCrossReference_0_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cNoteGroupsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNoteGroupsNoteGroupParserRuleCall_1_0 = (RuleCall)cNoteGroupsAssignment_1.eContents().get(0);
		private final Assignment cBarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBarBarlineEnumRuleCall_2_0 = (RuleCall)cBarAssignment_2.eContents().get(0);
		
		//LyricPhrase:
		//	('(' explicitPhrase=[TonePhrase] ')')?
		//	noteGroups+=NoteGroup+
		//	bar=Barline;
		@Override public ParserRule getRule() { return rule; }
		
		//('(' explicitPhrase=[TonePhrase] ')')? noteGroups+=NoteGroup+ bar=Barline
		public Group getGroup() { return cGroup; }
		
		//('(' explicitPhrase=[TonePhrase] ')')?
		public Group getGroup_0() { return cGroup_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }
		
		//explicitPhrase=[TonePhrase]
		public Assignment getExplicitPhraseAssignment_0_1() { return cExplicitPhraseAssignment_0_1; }
		
		//[TonePhrase]
		public CrossReference getExplicitPhraseTonePhraseCrossReference_0_1_0() { return cExplicitPhraseTonePhraseCrossReference_0_1_0; }
		
		//ID
		public RuleCall getExplicitPhraseTonePhraseIDTerminalRuleCall_0_1_0_1() { return cExplicitPhraseTonePhraseIDTerminalRuleCall_0_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }
		
		//noteGroups+=NoteGroup+
		public Assignment getNoteGroupsAssignment_1() { return cNoteGroupsAssignment_1; }
		
		//NoteGroup
		public RuleCall getNoteGroupsNoteGroupParserRuleCall_1_0() { return cNoteGroupsNoteGroupParserRuleCall_1_0; }
		
		//bar=Barline
		public Assignment getBarAssignment_2() { return cBarAssignment_2; }
		
		//Barline
		public RuleCall getBarBarlineEnumRuleCall_2_0() { return cBarBarlineEnumRuleCall_2_0; }
	}
	public class NoteGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.NoteGroup");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Alternatives cAlternatives_0_0 = (Alternatives)cGroup_0.eContents().get(0);
		private final Group cGroup_0_0_0 = (Group)cAlternatives_0_0.eContents().get(0);
		private final Assignment cSyllablesAssignment_0_0_0_0 = (Assignment)cGroup_0_0_0.eContents().get(0);
		private final RuleCall cSyllablesIDTerminalRuleCall_0_0_0_0_0 = (RuleCall)cSyllablesAssignment_0_0_0_0.eContents().get(0);
		private final Group cGroup_0_0_0_1 = (Group)cGroup_0_0_0.eContents().get(1);
		private final Assignment cSyllablesAssignment_0_0_0_1_0 = (Assignment)cGroup_0_0_0_1.eContents().get(0);
		private final RuleCall cSyllablesHYPHENTerminalRuleCall_0_0_0_1_0_0 = (RuleCall)cSyllablesAssignment_0_0_0_1_0.eContents().get(0);
		private final Group cGroup_0_0_1 = (Group)cAlternatives_0_0.eContents().get(1);
		private final Assignment cSyllablesAssignment_0_0_1_0 = (Assignment)cGroup_0_0_1.eContents().get(0);
		private final RuleCall cSyllablesHYPHENTerminalRuleCall_0_0_1_0_0 = (RuleCall)cSyllablesAssignment_0_0_1_0.eContents().get(0);
		private final Assignment cSyllablesAssignment_0_0_1_1 = (Assignment)cGroup_0_0_1.eContents().get(1);
		private final RuleCall cSyllablesIDTerminalRuleCall_0_0_1_1_0 = (RuleCall)cSyllablesAssignment_0_0_1_1.eContents().get(0);
		private final Assignment cSyllablesAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cSyllablesEXTENDERTerminalRuleCall_0_1_0 = (RuleCall)cSyllablesAssignment_0_1.eContents().get(0);
		private final Assignment cSyllablesAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cSyllablesSKIPTerminalRuleCall_1_0 = (RuleCall)cSyllablesAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final RuleCall cSTART_NOTE_GROUPTerminalRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Assignment cSyllablesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final Alternatives cSyllablesAlternatives_2_1_0 = (Alternatives)cSyllablesAssignment_2_1.eContents().get(0);
		private final RuleCall cSyllablesIDTerminalRuleCall_2_1_0_0 = (RuleCall)cSyllablesAlternatives_2_1_0.eContents().get(0);
		private final RuleCall cSyllablesHYPHENTerminalRuleCall_2_1_0_1 = (RuleCall)cSyllablesAlternatives_2_1_0.eContents().get(1);
		private final RuleCall cSyllablesEXTENDERTerminalRuleCall_2_1_0_2 = (RuleCall)cSyllablesAlternatives_2_1_0.eContents().get(2);
		private final RuleCall cEND_NOTE_GROUPTerminalRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		
		//NoteGroup:
		//	(syllables+=ID => (syllables+=HYPHEN)?
		//	| syllables+=HYPHEN syllables+=ID) syllables+=EXTENDER*
		//	| syllables+=SKIP
		//	// group of syllables to be repeated on the same pitch
		//	| START_NOTE_GROUP syllables+=(ID | HYPHEN | EXTENDER)+ END_NOTE_GROUP;
		@Override public ParserRule getRule() { return rule; }
		
		//(syllables+=ID => (syllables+=HYPHEN)? | syllables+=HYPHEN syllables+=ID) syllables+=EXTENDER* | syllables+=SKIP // group of syllables to be repeated on the same pitch
		//| START_NOTE_GROUP syllables+=(ID | HYPHEN | EXTENDER)+ END_NOTE_GROUP
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//(syllables+=ID => (syllables+=HYPHEN)? | syllables+=HYPHEN syllables+=ID) syllables+=EXTENDER*
		public Group getGroup_0() { return cGroup_0; }
		
		//syllables+=ID => (syllables+=HYPHEN)? | syllables+=HYPHEN syllables+=ID
		public Alternatives getAlternatives_0_0() { return cAlternatives_0_0; }
		
		//syllables+=ID => (syllables+=HYPHEN)?
		public Group getGroup_0_0_0() { return cGroup_0_0_0; }
		
		//syllables+=ID
		public Assignment getSyllablesAssignment_0_0_0_0() { return cSyllablesAssignment_0_0_0_0; }
		
		//ID
		public RuleCall getSyllablesIDTerminalRuleCall_0_0_0_0_0() { return cSyllablesIDTerminalRuleCall_0_0_0_0_0; }
		
		//=> (syllables+=HYPHEN)?
		public Group getGroup_0_0_0_1() { return cGroup_0_0_0_1; }
		
		//syllables+=HYPHEN
		public Assignment getSyllablesAssignment_0_0_0_1_0() { return cSyllablesAssignment_0_0_0_1_0; }
		
		//HYPHEN
		public RuleCall getSyllablesHYPHENTerminalRuleCall_0_0_0_1_0_0() { return cSyllablesHYPHENTerminalRuleCall_0_0_0_1_0_0; }
		
		//syllables+=HYPHEN syllables+=ID
		public Group getGroup_0_0_1() { return cGroup_0_0_1; }
		
		//syllables+=HYPHEN
		public Assignment getSyllablesAssignment_0_0_1_0() { return cSyllablesAssignment_0_0_1_0; }
		
		//HYPHEN
		public RuleCall getSyllablesHYPHENTerminalRuleCall_0_0_1_0_0() { return cSyllablesHYPHENTerminalRuleCall_0_0_1_0_0; }
		
		//syllables+=ID
		public Assignment getSyllablesAssignment_0_0_1_1() { return cSyllablesAssignment_0_0_1_1; }
		
		//ID
		public RuleCall getSyllablesIDTerminalRuleCall_0_0_1_1_0() { return cSyllablesIDTerminalRuleCall_0_0_1_1_0; }
		
		//syllables+=EXTENDER*
		public Assignment getSyllablesAssignment_0_1() { return cSyllablesAssignment_0_1; }
		
		//EXTENDER
		public RuleCall getSyllablesEXTENDERTerminalRuleCall_0_1_0() { return cSyllablesEXTENDERTerminalRuleCall_0_1_0; }
		
		//syllables+=SKIP
		public Assignment getSyllablesAssignment_1() { return cSyllablesAssignment_1; }
		
		//SKIP
		public RuleCall getSyllablesSKIPTerminalRuleCall_1_0() { return cSyllablesSKIPTerminalRuleCall_1_0; }
		
		//START_NOTE_GROUP syllables+=(ID | HYPHEN | EXTENDER)+ END_NOTE_GROUP
		public Group getGroup_2() { return cGroup_2; }
		
		//START_NOTE_GROUP
		public RuleCall getSTART_NOTE_GROUPTerminalRuleCall_2_0() { return cSTART_NOTE_GROUPTerminalRuleCall_2_0; }
		
		//syllables+=(ID | HYPHEN | EXTENDER)+
		public Assignment getSyllablesAssignment_2_1() { return cSyllablesAssignment_2_1; }
		
		//(ID | HYPHEN | EXTENDER)
		public Alternatives getSyllablesAlternatives_2_1_0() { return cSyllablesAlternatives_2_1_0; }
		
		//ID
		public RuleCall getSyllablesIDTerminalRuleCall_2_1_0_0() { return cSyllablesIDTerminalRuleCall_2_1_0_0; }
		
		//HYPHEN
		public RuleCall getSyllablesHYPHENTerminalRuleCall_2_1_0_1() { return cSyllablesHYPHENTerminalRuleCall_2_1_0_1; }
		
		//EXTENDER
		public RuleCall getSyllablesEXTENDERTerminalRuleCall_2_1_0_2() { return cSyllablesEXTENDERTerminalRuleCall_2_1_0_2; }
		
		//END_NOTE_GROUP
		public RuleCall getEND_NOTE_GROUPTerminalRuleCall_2_2() { return cEND_NOTE_GROUPTerminalRuleCall_2_2; }
	}
	public class NoteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.Note");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPitchAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPitchIDTerminalRuleCall_0_0 = (RuleCall)cPitchAssignment_0.eContents().get(0);
		private final Assignment cDurationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDurationDURATIONTerminalRuleCall_1_0 = (RuleCall)cDurationAssignment_1.eContents().get(0);
		
		///*
		// * Notes and keys
		// */ //enum Mode:
		////	major='major' | minor='minor'
		////;
		//Note:
		//	pitch=ID duration=DURATION?;
		@Override public ParserRule getRule() { return rule; }
		
		//pitch=ID duration=DURATION?
		public Group getGroup() { return cGroup; }
		
		//pitch=ID
		public Assignment getPitchAssignment_0() { return cPitchAssignment_0; }
		
		//ID
		public RuleCall getPitchIDTerminalRuleCall_0_0() { return cPitchIDTerminalRuleCall_0_0; }
		
		//duration=DURATION?
		public Assignment getDurationAssignment_1() { return cDurationAssignment_1; }
		
		//DURATION
		public RuleCall getDurationDURATIONTerminalRuleCall_1_0() { return cDurationDURATIONTerminalRuleCall_1_0; }
	}
	
	public class BarlineElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.Barline");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSingleEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSingleVerticalLineKeyword_0_0 = (Keyword)cSingleEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDoubleVerticalLineVerticalLineKeyword_1_0 = (Keyword)cDoubleEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Barline:
		//	single='|' | double='||';
		public EnumRule getRule() { return rule; }
		
		//single='|' | double='||'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//single='|'
		public EnumLiteralDeclaration getSingleEnumLiteralDeclaration_0() { return cSingleEnumLiteralDeclaration_0; }
		
		//'|'
		public Keyword getSingleVerticalLineKeyword_0_0() { return cSingleVerticalLineKeyword_0_0; }
		
		//double='||'
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_1() { return cDoubleEnumLiteralDeclaration_1; }
		
		//'||'
		public Keyword getDoubleVerticalLineVerticalLineKeyword_1_0() { return cDoubleVerticalLineVerticalLineKeyword_1_0; }
	}
	
	private final ScriptElements pScript;
	private final ToneElements pTone;
	private final VoiceNameElements pVoiceName;
	private final TonePhraseElements pTonePhrase;
	private final VoicePhraseElements pVoicePhrase;
	private final ChantElements pChant;
	private final LyricPhraseElements pLyricPhrase;
	private final BarlineElements eBarline;
	private final NoteGroupElements pNoteGroup;
	private final NoteElements pNote;
	private final TerminalRule tID;
	private final TerminalRule tSTRING;
	private final TerminalRule tDURATION;
	private final TerminalRule tHYPHEN;
	private final TerminalRule tEXTENDER;
	private final TerminalRule tSKIP;
	private final TerminalRule tSTART_NOTE_GROUP;
	private final TerminalRule tEND_NOTE_GROUP;
	private final TerminalRule tBEGIN;
	private final TerminalRule tEND;
	private final TerminalRule tML_COMMENT;
	private final TerminalRule tSL_COMMENT;
	private final TerminalRule tWS;
	private final TerminalRule tANY_OTHER;
	
	private final Grammar grammar;

	@Inject
	public LilyChantGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pScript = new ScriptElements();
		this.pTone = new ToneElements();
		this.pVoiceName = new VoiceNameElements();
		this.pTonePhrase = new TonePhraseElements();
		this.pVoicePhrase = new VoicePhraseElements();
		this.pChant = new ChantElements();
		this.pLyricPhrase = new LyricPhraseElements();
		this.eBarline = new BarlineElements();
		this.pNoteGroup = new NoteGroupElements();
		this.pNote = new NoteElements();
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.ID");
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.STRING");
		this.tDURATION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.DURATION");
		this.tHYPHEN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.HYPHEN");
		this.tEXTENDER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.EXTENDER");
		this.tSKIP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.SKIP");
		this.tSTART_NOTE_GROUP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.START_NOTE_GROUP");
		this.tEND_NOTE_GROUP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.END_NOTE_GROUP");
		this.tBEGIN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.BEGIN");
		this.tEND = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.END");
		this.tML_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.ML_COMMENT");
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.SL_COMMENT");
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.WS");
		this.tANY_OTHER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.lilychant.LilyChant.ANY_OTHER");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.lilychant.LilyChant".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//Script:
	//	tones+=Tone*
	//	//	ensemble=Ensemble
	//	chants+=Chant*;
	public ScriptElements getScriptAccess() {
		return pScript;
	}
	
	public ParserRule getScriptRule() {
		return getScriptAccess().getRule();
	}
	
	///*
	// * Tone definitions
	// */ // TODO VOICE NAMES SHOULD BE GLOBAL
	//Tone:
	//	'Tone' name=ID //'key' key=ID
	//	BEGIN
	//	'Voices'
	//	BEGIN
	//	voiceNames+=VoiceName+
	//	END
	//	phrases+=TonePhrase+
	//	END;
	public ToneElements getToneAccess() {
		return pTone;
	}
	
	public ParserRule getToneRule() {
		return getToneAccess().getRule();
	}
	
	//VoiceName:
	//	name=ID;
	public VoiceNameElements getVoiceNameAccess() {
		return pVoiceName;
	}
	
	public ParserRule getVoiceNameRule() {
		return getVoiceNameAccess().getRule();
	}
	
	//TonePhrase:
	//	'Phrase' name=ID
	//	BEGIN
	//	voices+=VoicePhrase+
	//	END;
	public TonePhraseElements getTonePhraseAccess() {
		return pTonePhrase;
	}
	
	public ParserRule getTonePhraseRule() {
		return getTonePhraseAccess().getRule();
	}
	
	//VoicePhrase:
	//	'Voice' name=[VoiceName] BEGIN
	//	notes+=Note+
	//	END;
	public VoicePhraseElements getVoicePhraseAccess() {
		return pVoicePhrase;
	}
	
	public ParserRule getVoicePhraseRule() {
		return getVoicePhraseAccess().getRule();
	}
	
	/////*
	//// * Ensemble
	//// */
	////
	////Ensemble:
	////	'ensemble' ':'
	////	'top' 'staff' ':' BEGIN voices+=[VoiceName]+ END
	////	'bottom' 'staff' ':' BEGIN voices+=[VoiceName]+ END
	////;
	///*
	// * Chants
	// */ Chant:
	//	'Chant' name=STRING? 'Tone' tone=[Tone] BEGIN
	//	phrases+=LyricPhrase+
	//	END;
	public ChantElements getChantAccess() {
		return pChant;
	}
	
	public ParserRule getChantRule() {
		return getChantAccess().getRule();
	}
	
	//LyricPhrase:
	//	('(' explicitPhrase=[TonePhrase] ')')?
	//	noteGroups+=NoteGroup+
	//	bar=Barline;
	public LyricPhraseElements getLyricPhraseAccess() {
		return pLyricPhrase;
	}
	
	public ParserRule getLyricPhraseRule() {
		return getLyricPhraseAccess().getRule();
	}
	
	//enum Barline:
	//	single='|' | double='||';
	public BarlineElements getBarlineAccess() {
		return eBarline;
	}
	
	public EnumRule getBarlineRule() {
		return getBarlineAccess().getRule();
	}
	
	//NoteGroup:
	//	(syllables+=ID => (syllables+=HYPHEN)?
	//	| syllables+=HYPHEN syllables+=ID) syllables+=EXTENDER*
	//	| syllables+=SKIP
	//	// group of syllables to be repeated on the same pitch
	//	| START_NOTE_GROUP syllables+=(ID | HYPHEN | EXTENDER)+ END_NOTE_GROUP;
	public NoteGroupElements getNoteGroupAccess() {
		return pNoteGroup;
	}
	
	public ParserRule getNoteGroupRule() {
		return getNoteGroupAccess().getRule();
	}
	
	///*
	// * Notes and keys
	// */ //enum Mode:
	////	major='major' | minor='minor'
	////;
	//Note:
	//	pitch=ID duration=DURATION?;
	public NoteElements getNoteAccess() {
		return pNote;
	}
	
	public ParserRule getNoteRule() {
		return getNoteAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '\\u0400'..'\\u04ff' | ',' | '\'' | ';' | ':' | '.')*;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	}
	
	//terminal DURATION:
	//	'1' | '2' | '4' | '8' | '16' | '\breve'+;
	public TerminalRule getDURATIONRule() {
		return tDURATION;
	}
	
	//terminal HYPHEN:
	//	'--';
	public TerminalRule getHYPHENRule() {
		return tHYPHEN;
	}
	
	//terminal EXTENDER:
	//	'__';
	public TerminalRule getEXTENDERRule() {
		return tEXTENDER;
	}
	
	//terminal SKIP:
	//	'_';
	public TerminalRule getSKIPRule() {
		return tSKIP;
	}
	
	//terminal START_NOTE_GROUP:
	//	'<';
	public TerminalRule getSTART_NOTE_GROUPRule() {
		return tSTART_NOTE_GROUP;
	}
	
	//terminal END_NOTE_GROUP:
	//	'>';
	public TerminalRule getEND_NOTE_GROUPRule() {
		return tEND_NOTE_GROUP;
	}
	
	//terminal BEGIN:
	//	'synthetic:BEGIN';
	public TerminalRule getBEGINRule() {
		return tBEGIN;
	}
	
	//terminal END:
	//	'synthetic:END';
	public TerminalRule getENDRule() {
		return tEND;
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return tML_COMMENT;
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return tWS;
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return tANY_OTHER;
	}
}
