/*
 * generated by Xtext 2.9.2
 */
package org.lilychant.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class LilyChantScopeProvider extends AbstractLilyChantScopeProvider {

}
