/*
 * generated by Xtext 2.9.2
 */
package org.lilychant


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LilyChantStandaloneSetup extends LilyChantStandaloneSetupGenerated {

	def static void doSetup() {
		new LilyChantStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
