/*
 * generated by Xtext 2.9.1
 */
package org.lilychant.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLilyChantScopeProvider extends DelegatingScopeProvider {
}
