/**
 * generated by Xtext 2.40.0
 */
package org.lilychant.lilyChantScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extender Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getExtenderRule()
 * @model
 * @generated
 */
public interface ExtenderRule extends Syllable
{
} // ExtenderRule
