/**
 * generated by Xtext 2.40.0
 */
package org.lilychant.lilyChantScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hyphen Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getHyphenRule()
 * @model
 * @generated
 */
public interface HyphenRule extends Syllable
{
} // HyphenRule
