/**
 * generated by Xtext 2.9.2
 */
package org.lilychant.lilyChantScript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lyric Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.lilychant.lilyChantScript.LyricPhrase#getNotes <em>Notes</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.LyricPhrase#getNoteGroups <em>Note Groups</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getLyricPhrase()
 * @model
 * @generated
 */
public interface LyricPhrase extends EObject
{
  /**
   * Returns the value of the '<em><b>Notes</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Notes</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notes</em>' reference.
   * @see #setNotes(TonePhrase)
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getLyricPhrase_Notes()
   * @model
   * @generated
   */
  TonePhrase getNotes();

  /**
   * Sets the value of the '{@link org.lilychant.lilyChantScript.LyricPhrase#getNotes <em>Notes</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Notes</em>' reference.
   * @see #getNotes()
   * @generated
   */
  void setNotes(TonePhrase value);

  /**
   * Returns the value of the '<em><b>Note Groups</b></em>' containment reference list.
   * The list contents are of type {@link org.lilychant.lilyChantScript.NoteGroup}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Note Groups</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Note Groups</em>' containment reference list.
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getLyricPhrase_NoteGroups()
   * @model containment="true"
   * @generated
   */
  EList<NoteGroup> getNoteGroups();

} // LyricPhrase
