/**
 * generated by Xtext 2.11.0
 */
package org.lilychant.lilyChantScript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lyric Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.lilychant.lilyChantScript.LyricPhrase#getExplicitPhrase <em>Explicit Phrase</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.LyricPhrase#getNoteGroups <em>Note Groups</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.LyricPhrase#getBar <em>Bar</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getLyricPhrase()
 * @model
 * @generated
 */
public interface LyricPhrase extends EObject
{
  /**
   * Returns the value of the '<em><b>Explicit Phrase</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Explicit Phrase</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Explicit Phrase</em>' reference.
   * @see #setExplicitPhrase(TonePhrase)
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getLyricPhrase_ExplicitPhrase()
   * @model
   * @generated
   */
  TonePhrase getExplicitPhrase();

  /**
   * Sets the value of the '{@link org.lilychant.lilyChantScript.LyricPhrase#getExplicitPhrase <em>Explicit Phrase</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Explicit Phrase</em>' reference.
   * @see #getExplicitPhrase()
   * @generated
   */
  void setExplicitPhrase(TonePhrase value);

  /**
   * Returns the value of the '<em><b>Note Groups</b></em>' containment reference list.
   * The list contents are of type {@link org.lilychant.lilyChantScript.NoteGroup}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Note Groups</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Note Groups</em>' containment reference list.
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getLyricPhrase_NoteGroups()
   * @model containment="true"
   * @generated
   */
  EList<NoteGroup> getNoteGroups();

  /**
   * Returns the value of the '<em><b>Bar</b></em>' attribute.
   * The literals are from the enumeration {@link org.lilychant.lilyChantScript.Barline}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bar</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bar</em>' attribute.
   * @see org.lilychant.lilyChantScript.Barline
   * @see #setBar(Barline)
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getLyricPhrase_Bar()
   * @model
   * @generated
   */
  Barline getBar();

  /**
   * Sets the value of the '{@link org.lilychant.lilyChantScript.LyricPhrase#getBar <em>Bar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bar</em>' attribute.
   * @see org.lilychant.lilyChantScript.Barline
   * @see #getBar()
   * @generated
   */
  void setBar(Barline value);

} // LyricPhrase
