/**
 * generated by Xtext 2.11.0
 */
package org.lilychant.lilyChantScript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Script</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.lilychant.lilyChantScript.Script#getTones <em>Tones</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.Script#getChants <em>Chants</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.Script#getFormat <em>Format</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getScript()
 * @model
 * @generated
 */
public interface Script extends EObject
{
  /**
   * Returns the value of the '<em><b>Tones</b></em>' containment reference list.
   * The list contents are of type {@link org.lilychant.lilyChantScript.Tone}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tones</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tones</em>' containment reference list.
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getScript_Tones()
   * @model containment="true"
   * @generated
   */
  EList<Tone> getTones();

  /**
   * Returns the value of the '<em><b>Chants</b></em>' containment reference list.
   * The list contents are of type {@link org.lilychant.lilyChantScript.Chant}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Chants</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chants</em>' containment reference list.
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getScript_Chants()
   * @model containment="true"
   * @generated
   */
  EList<Chant> getChants();

  /**
   * Returns the value of the '<em><b>Format</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Format</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' containment reference.
   * @see #setFormat(Format)
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getScript_Format()
   * @model containment="true"
   * @generated
   */
  Format getFormat();

  /**
   * Sets the value of the '{@link org.lilychant.lilyChantScript.Script#getFormat <em>Format</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' containment reference.
   * @see #getFormat()
   * @generated
   */
  void setFormat(Format value);

} // Script
