/**
 * generated by Xtext 2.40.0
 */
package org.lilychant.lilyChantScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Skip Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getSkipRule()
 * @model
 * @generated
 */
public interface SkipRule extends Syllable
{
} // SkipRule
