/**
 * generated by Xtext 2.9.1
 */
package org.lilychant.lilyChantScript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tone Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.lilychant.lilyChantScript.TonePhrase#getName <em>Name</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.TonePhrase#getVoices <em>Voices</em>}</li>
 * </ul>
 *
 * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getTonePhrase()
 * @model
 * @generated
 */
public interface TonePhrase extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getTonePhrase_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.lilychant.lilyChantScript.TonePhrase#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Voices</b></em>' containment reference list.
   * The list contents are of type {@link org.lilychant.lilyChantScript.VoicePhrase}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Voices</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Voices</em>' containment reference list.
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getTonePhrase_Voices()
   * @model containment="true"
   * @generated
   */
  EList<VoicePhrase> getVoices();

} // TonePhrase
