/**
 * generated by Xtext 2.40.0
 */
package org.lilychant.lilyChantScript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tone</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.lilychant.lilyChantScript.Tone#getName <em>Name</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.Tone#getVoiceNames <em>Voice Names</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.Tone#getPhrases <em>Phrases</em>}</li>
 * </ul>
 *
 * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getTone()
 * @model
 * @generated
 */
public interface Tone extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getTone_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.lilychant.lilyChantScript.Tone#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Voice Names</b></em>' containment reference list.
   * The list contents are of type {@link org.lilychant.lilyChantScript.VoiceName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Voice Names</em>' containment reference list.
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getTone_VoiceNames()
   * @model containment="true"
   * @generated
   */
  EList<VoiceName> getVoiceNames();

  /**
   * Returns the value of the '<em><b>Phrases</b></em>' containment reference list.
   * The list contents are of type {@link org.lilychant.lilyChantScript.TonePhrase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phrases</em>' containment reference list.
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getTone_Phrases()
   * @model containment="true"
   * @generated
   */
  EList<TonePhrase> getPhrases();

} // Tone
