/**
 * generated by Xtext 2.40.0
 */
package org.lilychant.lilyChantScript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Voice Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.lilychant.lilyChantScript.VoicePhrase#getName <em>Name</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.VoicePhrase#getNotes <em>Notes</em>}</li>
 * </ul>
 *
 * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getVoicePhrase()
 * @model
 * @generated
 */
public interface VoicePhrase extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(VoiceName)
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getVoicePhrase_Name()
   * @model
   * @generated
   */
  VoiceName getName();

  /**
   * Sets the value of the '{@link org.lilychant.lilyChantScript.VoicePhrase#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(VoiceName value);

  /**
   * Returns the value of the '<em><b>Notes</b></em>' containment reference list.
   * The list contents are of type {@link org.lilychant.lilyChantScript.Note}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notes</em>' containment reference list.
   * @see org.lilychant.lilyChantScript.LilyChantScriptPackage#getVoicePhrase_Notes()
   * @model containment="true"
   * @generated
   */
  EList<Note> getNotes();

} // VoicePhrase
