/**
 * generated by Xtext 2.11.0
 */
package org.lilychant.lilyChantScript.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.lilychant.lilyChantScript.Format;
import org.lilychant.lilyChantScript.LilyChantScriptPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Format</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.lilychant.lilyChantScript.impl.FormatImpl#isRaggedbottom <em>Raggedbottom</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.impl.FormatImpl#isRaggedlastbottom <em>Raggedlastbottom</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class FormatImpl extends MinimalEObjectImpl.Container implements Format
{
  /**
   * The default value of the '{@link #isRaggedbottom() <em>Raggedbottom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRaggedbottom()
   * @generated
   * @ordered
   */
  protected static final boolean RAGGEDBOTTOM_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isRaggedbottom() <em>Raggedbottom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRaggedbottom()
   * @generated
   * @ordered
   */
  protected boolean raggedbottom = RAGGEDBOTTOM_EDEFAULT;

  /**
   * The default value of the '{@link #isRaggedlastbottom() <em>Raggedlastbottom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRaggedlastbottom()
   * @generated
   * @ordered
   */
  protected static final boolean RAGGEDLASTBOTTOM_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isRaggedlastbottom() <em>Raggedlastbottom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRaggedlastbottom()
   * @generated
   * @ordered
   */
  protected boolean raggedlastbottom = RAGGEDLASTBOTTOM_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FormatImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LilyChantScriptPackage.Literals.FORMAT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isRaggedbottom()
  {
    return raggedbottom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRaggedbottom(boolean newRaggedbottom)
  {
    boolean oldRaggedbottom = raggedbottom;
    raggedbottom = newRaggedbottom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LilyChantScriptPackage.FORMAT__RAGGEDBOTTOM, oldRaggedbottom, raggedbottom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isRaggedlastbottom()
  {
    return raggedlastbottom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRaggedlastbottom(boolean newRaggedlastbottom)
  {
    boolean oldRaggedlastbottom = raggedlastbottom;
    raggedlastbottom = newRaggedlastbottom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LilyChantScriptPackage.FORMAT__RAGGEDLASTBOTTOM, oldRaggedlastbottom, raggedlastbottom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.FORMAT__RAGGEDBOTTOM:
        return isRaggedbottom();
      case LilyChantScriptPackage.FORMAT__RAGGEDLASTBOTTOM:
        return isRaggedlastbottom();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.FORMAT__RAGGEDBOTTOM:
        setRaggedbottom((Boolean)newValue);
        return;
      case LilyChantScriptPackage.FORMAT__RAGGEDLASTBOTTOM:
        setRaggedlastbottom((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.FORMAT__RAGGEDBOTTOM:
        setRaggedbottom(RAGGEDBOTTOM_EDEFAULT);
        return;
      case LilyChantScriptPackage.FORMAT__RAGGEDLASTBOTTOM:
        setRaggedlastbottom(RAGGEDLASTBOTTOM_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.FORMAT__RAGGEDBOTTOM:
        return raggedbottom != RAGGEDBOTTOM_EDEFAULT;
      case LilyChantScriptPackage.FORMAT__RAGGEDLASTBOTTOM:
        return raggedlastbottom != RAGGEDLASTBOTTOM_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (raggedbottom: ");
    result.append(raggedbottom);
    result.append(", raggedlastbottom: ");
    result.append(raggedlastbottom);
    result.append(')');
    return result.toString();
  }

} //FormatImpl
