/**
 * generated by Xtext 2.9.1
 */
package org.lilychant.lilyChantScript.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.lilychant.lilyChantScript.Barline;
import org.lilychant.lilyChantScript.LilyChantScriptPackage;
import org.lilychant.lilyChantScript.LyricPhrase;
import org.lilychant.lilyChantScript.NoteGroup;
import org.lilychant.lilyChantScript.TonePhrase;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lyric Phrase</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.lilychant.lilyChantScript.impl.LyricPhraseImpl#getExplicitPhrase <em>Explicit Phrase</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.impl.LyricPhraseImpl#getNoteGroups <em>Note Groups</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.impl.LyricPhraseImpl#getBar <em>Bar</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LyricPhraseImpl extends MinimalEObjectImpl.Container implements LyricPhrase
{
  /**
   * The cached value of the '{@link #getExplicitPhrase() <em>Explicit Phrase</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExplicitPhrase()
   * @generated
   * @ordered
   */
  protected TonePhrase explicitPhrase;

  /**
   * The cached value of the '{@link #getNoteGroups() <em>Note Groups</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoteGroups()
   * @generated
   * @ordered
   */
  protected EList<NoteGroup> noteGroups;

  /**
   * The default value of the '{@link #getBar() <em>Bar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBar()
   * @generated
   * @ordered
   */
  protected static final Barline BAR_EDEFAULT = Barline.SINGLE;

  /**
   * The cached value of the '{@link #getBar() <em>Bar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBar()
   * @generated
   * @ordered
   */
  protected Barline bar = BAR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LyricPhraseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LilyChantScriptPackage.Literals.LYRIC_PHRASE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TonePhrase getExplicitPhrase()
  {
    if (explicitPhrase != null && explicitPhrase.eIsProxy())
    {
      InternalEObject oldExplicitPhrase = (InternalEObject)explicitPhrase;
      explicitPhrase = (TonePhrase)eResolveProxy(oldExplicitPhrase);
      if (explicitPhrase != oldExplicitPhrase)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, LilyChantScriptPackage.LYRIC_PHRASE__EXPLICIT_PHRASE, oldExplicitPhrase, explicitPhrase));
      }
    }
    return explicitPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TonePhrase basicGetExplicitPhrase()
  {
    return explicitPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExplicitPhrase(TonePhrase newExplicitPhrase)
  {
    TonePhrase oldExplicitPhrase = explicitPhrase;
    explicitPhrase = newExplicitPhrase;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LilyChantScriptPackage.LYRIC_PHRASE__EXPLICIT_PHRASE, oldExplicitPhrase, explicitPhrase));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<NoteGroup> getNoteGroups()
  {
    if (noteGroups == null)
    {
      noteGroups = new EObjectContainmentEList<NoteGroup>(NoteGroup.class, this, LilyChantScriptPackage.LYRIC_PHRASE__NOTE_GROUPS);
    }
    return noteGroups;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Barline getBar()
  {
    return bar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBar(Barline newBar)
  {
    Barline oldBar = bar;
    bar = newBar == null ? BAR_EDEFAULT : newBar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LilyChantScriptPackage.LYRIC_PHRASE__BAR, oldBar, bar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.LYRIC_PHRASE__NOTE_GROUPS:
        return ((InternalEList<?>)getNoteGroups()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.LYRIC_PHRASE__EXPLICIT_PHRASE:
        if (resolve) return getExplicitPhrase();
        return basicGetExplicitPhrase();
      case LilyChantScriptPackage.LYRIC_PHRASE__NOTE_GROUPS:
        return getNoteGroups();
      case LilyChantScriptPackage.LYRIC_PHRASE__BAR:
        return getBar();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.LYRIC_PHRASE__EXPLICIT_PHRASE:
        setExplicitPhrase((TonePhrase)newValue);
        return;
      case LilyChantScriptPackage.LYRIC_PHRASE__NOTE_GROUPS:
        getNoteGroups().clear();
        getNoteGroups().addAll((Collection<? extends NoteGroup>)newValue);
        return;
      case LilyChantScriptPackage.LYRIC_PHRASE__BAR:
        setBar((Barline)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.LYRIC_PHRASE__EXPLICIT_PHRASE:
        setExplicitPhrase((TonePhrase)null);
        return;
      case LilyChantScriptPackage.LYRIC_PHRASE__NOTE_GROUPS:
        getNoteGroups().clear();
        return;
      case LilyChantScriptPackage.LYRIC_PHRASE__BAR:
        setBar(BAR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.LYRIC_PHRASE__EXPLICIT_PHRASE:
        return explicitPhrase != null;
      case LilyChantScriptPackage.LYRIC_PHRASE__NOTE_GROUPS:
        return noteGroups != null && !noteGroups.isEmpty();
      case LilyChantScriptPackage.LYRIC_PHRASE__BAR:
        return bar != BAR_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (bar: ");
    result.append(bar);
    result.append(')');
    return result.toString();
  }

} //LyricPhraseImpl
