/**
 * generated by Xtext 2.11.0
 */
package org.lilychant.lilyChantScript.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.lilychant.lilyChantScript.LilyChantScriptPackage;
import org.lilychant.lilyChantScript.NoteGroup;
import org.lilychant.lilyChantScript.Syllable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Note Group</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.lilychant.lilyChantScript.impl.NoteGroupImpl#getSyllables <em>Syllables</em>}</li>
 *   <li>{@link org.lilychant.lilyChantScript.impl.NoteGroupImpl#isNoemphasis <em>Noemphasis</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class NoteGroupImpl extends MinimalEObjectImpl.Container implements NoteGroup
{
  /**
   * The cached value of the '{@link #getSyllables() <em>Syllables</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSyllables()
   * @generated
   * @ordered
   */
  protected EList<Syllable> syllables;

  /**
   * The default value of the '{@link #isNoemphasis() <em>Noemphasis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNoemphasis()
   * @generated
   * @ordered
   */
  protected static final boolean NOEMPHASIS_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isNoemphasis() <em>Noemphasis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNoemphasis()
   * @generated
   * @ordered
   */
  protected boolean noemphasis = NOEMPHASIS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NoteGroupImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LilyChantScriptPackage.Literals.NOTE_GROUP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Syllable> getSyllables()
  {
    if (syllables == null)
    {
      syllables = new EObjectContainmentEList<Syllable>(Syllable.class, this, LilyChantScriptPackage.NOTE_GROUP__SYLLABLES);
    }
    return syllables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isNoemphasis()
  {
    return noemphasis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNoemphasis(boolean newNoemphasis)
  {
    boolean oldNoemphasis = noemphasis;
    noemphasis = newNoemphasis;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LilyChantScriptPackage.NOTE_GROUP__NOEMPHASIS, oldNoemphasis, noemphasis));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.NOTE_GROUP__SYLLABLES:
        return ((InternalEList<?>)getSyllables()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.NOTE_GROUP__SYLLABLES:
        return getSyllables();
      case LilyChantScriptPackage.NOTE_GROUP__NOEMPHASIS:
        return isNoemphasis();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.NOTE_GROUP__SYLLABLES:
        getSyllables().clear();
        getSyllables().addAll((Collection<? extends Syllable>)newValue);
        return;
      case LilyChantScriptPackage.NOTE_GROUP__NOEMPHASIS:
        setNoemphasis((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.NOTE_GROUP__SYLLABLES:
        getSyllables().clear();
        return;
      case LilyChantScriptPackage.NOTE_GROUP__NOEMPHASIS:
        setNoemphasis(NOEMPHASIS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LilyChantScriptPackage.NOTE_GROUP__SYLLABLES:
        return syllables != null && !syllables.isEmpty();
      case LilyChantScriptPackage.NOTE_GROUP__NOEMPHASIS:
        return noemphasis != NOEMPHASIS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (noemphasis: ");
    result.append(noemphasis);
    result.append(')');
    return result.toString();
  }

} //NoteGroupImpl
