/**
 * generated by Xtext 2.40.0
 */
package org.lilychant.lilyChantScript.impl;

import org.eclipse.emf.ecore.EClass;

import org.lilychant.lilyChantScript.LilyChantScriptPackage;
import org.lilychant.lilyChantScript.SkipRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Skip Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SkipRuleImpl extends SyllableImpl implements SkipRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SkipRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LilyChantScriptPackage.Literals.SKIP_RULE;
  }

} //SkipRuleImpl
