/*
 * generated by Xtext 2.40.0
 */
package org.lilychant.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.lilychant.ui.internal.LilychantActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LilyChantExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LilychantActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LilychantActivator activator = LilychantActivator.getInstance();
		return activator != null ? activator.getInjector(LilychantActivator.ORG_LILYCHANT_LILYCHANT) : null;
	}

}
