/*
 * generated by Xtext 2.9.2
 */
package org.lilychant.script.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class LilyChantScriptWebModule extends AbstractLilyChantScriptWebModule {
}
